# Copyright (C) 2020 REVERE
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2020-03-30

version: '2.3'

# These services run on the computing node communicating with the platform sensors & vehicle CAN.

services:
######################################################################################
#
# Microservices for RHINO (Volvo FH16), Vehicle View CID = 100.
#
######################################################################################
    # Relay and downsample Envelopes from CID 101 to CID 100 (for opendlv-vehicle-view).
#    relay-downsample-101-100:
#        container_name: relay-downsample-101-100
#        image: chrberger/cluon-relay-multi:v0.0.4
#        cpuset: "0"
#        restart: always
#        network_mode: "host"
#        cap_add:
#        - SYS_NICE
#        entrypoint: ""
#        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=101 --cid-to=100 --downsample=19:10,49:1,51:1,191:5,195:1,196:5,197:5,198:5,199:5,200:1,203:5,204:5,205:5,206:5,1017:1,1030:1,1031:1,1033:1,1046:10,1051:1,1116:1,1118:1"


    ###########################################################################
    # Dump can2
    record-can2:
        container_name: record-can
        image: candump:latest
        restart: always
        network_mode: "host"
        privileged: true
        volumes:
        - $HOME/recordings:/recordings
        - $PWD/candumper.sh:/candumper.sh
        working_dir: /recordings
        entrypoint: ""
        command: "/candumper.sh can2"
