# Copyright (C) 2020 REVERE
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2020-04-30

version: '2.3'

# These services run on the a Platform Computing Node which has communication with platform sensors & vehicle CAN.

services:
######################################################################################
#
# Microservices for RHINO (Volvo FH16), Vehicle View CID = 100.
#
######################################################################################
    # Relay and downsample Envelopes from CID 101 to CID 100 (for opendlv-vehicle-view).
    relay-downsample-101-100:
        container_name: relay-downsample-101-100
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "0"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=101 --cid-to=100 --downsample=19:10,49:1,51:1,191:5,195:1,196:5,197:5,198:5,199:5,200:1,203:5,204:5,205:5,206:5,1017:1,1030:1,1031:1,1033:1,1046:10,1051:1,1116:1,1118:1"

    # Relay cluon.data.RecorderCommand.
    relay-recordercommand-actuationrequest-100-101:
        container_name: relay-recordercommand-actuationrequest-100-101
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "0"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=100 --cid-to=101 --keep=11,160"

    ###########################################################################
    # Dump all containers from CID 101 on request.
    record-101:
        container_name: record-101
        image: chrberger/cluon-record-multi:v0.0.1
        cpuset: "0"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings:/recordings
        working_dir: /recordings
        command: "--cid=101 --remote --recsuffix=-all"

    ###########################################################################
    # OxTS GPS (10.40.40.80)
    dev-gps-ncom:
        container_name: dev-gps-ncom
        image: registry.git.chalmers.se/chalmers-revere/opendlv-device-gps-ncom:v1.0.10
        cpuset: "1"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/opendlv-device-gps-ncom --ncom_ip=0.0.0.0 --ncom_port=3000 --cid=101 --id=0"

    ###########################################################################
    # Axis camera including recording functionality with remote start/stop.
#    dev-camera-axis0:
#        container_name: dev-camera-axis0
#        image: chalmersrevere/opendlv-device-camera-rtp-amd64:v0.0.6
#        cpuset: "5"
#        restart: "always"
#        network_mode: "host"
#        volumes:
#        -$HOME/recordings:/recordings
#        cap_add:
#        - SYS_NICE
#        command: "nice -n -8 /usr/bin/opendlv-device-camera-rtp --url=rtsp://10.40.45.50/axis-media/media.amp?camera=1 --client-port-udp-a=35000 --remote --recsuffix=-all --cid=101 --id=0 "
#        runtime: runc

#    qsv-h264-thumbnail-axis-out:
#        container_name: qsv-h264-thumbnail-axis-out
#        image: chrberger/video-qsv-h264-encoder:v0.0.4
#        depends_on:
#        - dev-camera-axis0
#        cpuset: "2"
#        devices:
#        - /dev/dri/renderD128
#        restart: always
#        network_mode: "host"
#        ipc: "host"
#        volumes:
#        - /tmp:/tmp
#        cap_add:
#        - SYS_NICE
#        entrypoint: ""
#        command: "nice -n -7 /usr/bin/video-qsv-h264-encoder --name=axis-out.i420 --width=1280 --height=720 --bitrate=3000 --crop.x=320 --crop.y=120 --crop.width=640 --crop.height=480 --downsample=3 --cid=100 --id=0"

    ############################################################################
    # CAN interface to access Rhino
    # if write privileges are needed add '--enablethrottle --enablebrake --enablesteering' to command line
    opendlv-gw-can-rhino:
        container_name: dlv-gw-can-rhino
#        image: registry.git.chalmers.se/chalmers-revere/opendlv-gw-can-rhino:v1.0.1
        image: test:latest
        cpuset: "1"
        restart: always
        network_mode: "host"
        privileged: true
        command: "--can=can0 --cid=101 --id=1"
#        command: "--can=can0 --enablethrottle --enablebrake --enablesteering --cid=101 --id=1"

    ############################################################################
    # Web-application for viewing vehicle data.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        cpuset: "0"
        restart: always
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=100
        - PLAYBACK_OD4SESSION_CID=200
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Rhino
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -15 node index.js"

######################################################################################
#
# END
#
######################################################################################
