# Copyright (C) 2020 REVERE
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2020-03-30

version: '2.3'

# These services run on the computing node communicating with the platform sensors & vehicle CAN.

services:
######################################################################################
#
# Microservices for RHINO (Volvo FH16) with Vehicle View CID = 100.
#
######################################################################################

    # Relay and downsample Envelopes from CID 101 to CID 100 (for opendlv-vehicle-view).
#    relay-downsample-101-100:
#        container_name: relay-downsample-101-100
#        image: chrberger/cluon-relay-multi:v0.0.4
#        cpuset: "0"
#        restart: always
#        network_mode: "host"
#        cap_add:
#        - SYS_NICE
#        entrypoint: ""
#        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=101 --cid-to=100 --downsample=""

    ###########################################################################
    # Axis camera including recording functionality with remote start/stop.
          #command: "nice -n -8 /usr/bin/opendlv-device-camera-rtp --url=rtsp://10.40.41.50/axis-media/media.amp?camera=1 --client-port-udp-a=35000 --remote --recsuffix=-all --cid=100 --id=3 --name=axis0."
    dev-axis-front-rtp:
        container_name: axis-front-rtp
        image: chalmersrevere/opendlv-device-camera-rtp-amd64:v0.0.3
        cpuset: "0"
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - $HOME/recordings:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/opendlv-device-camera-rtp --url=rtsp://10.40.41.50/axis-media/media.amp\\?camera=1 --cid=112 --id=0 --client-port-udp-a=35000 --name=abc --remote --recsuffix=-axis-front"
        runtime: runc

    dev-axis-front:
        container_name: axis-front
        image: chalmersrevere/opendlv-device-camera-mjpegoverhttp-multi:v0.0.3
        cpuset: "2"
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/opendlv-device-camera-mjpegoverhttp --url=http://10.40.41.50/axis-cgi/mjpg/video.cgi\\?channel=0\\&.mjpg\\&resolution=640x480\\&fps=10\\&compression=40\\&videocodec=jpeg --width=640 --height=480 --cid=113 --id=0 --remote --name.i420=axisfront.i420 --name.argb=axisfront.argb --skip.argb"
        runtime: runc

    axis-front-video-qsv-h264-encoder-amd64:
        container_name: axis-front-qsv
        image: chrberger/qsv-h264-encoder:v0.0.5
        restart: on-failure
        depends_on:
        - dev-axis-front
        devices:
        - /dev/dri/renderD128
        cpuset: "2"
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/video-qsv-h264-encoder --cid=100 --id=0 --name=axisfront.i420 --width=640 --height=480 --bitrate=8000 --downsample=2"
        runtime: runc


    ############################################################################
    # Web-application for viewing vehicle data.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        cpuset: "0"
        restart: always
        network_mode: "host"
        volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=100
        - PLAYBACK_OD4SESSION_CID=200
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Rhino
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -15 node index.js"

######################################################################################
#
# END
#
######################################################################################
